### ISSUE TITLE
Unable to render title from within components with OnAfterRenderAsync

### ISSUE THREAD

**Issue by Xeevis** [jsakamoto/Toolbelt.Blazor.HeadElement#19]
Hello. I'm trying to create component that would display current page title. Problem is, it doesn't work when used with OnAfterRenderAsync, probably because it's fired before the title is set as any later call does work.

```razor
<h1>@title</h1> @* null *@
@code {
  string title;
  protected override async Task OnAfterRenderAsync(bool firstRender)
  {
    if (firstRender)
    {
      title = await HeadElementHelper.GetTitleAsync();
    }
  }
}
```
Perhaps event would be of help here? Something like

```csharp
protected override void OnInitialized()
{
    HeadElementHelper.TitleChanged += OnTitleChanged;    
}

private void OnTitleChanged(object sender, TitleChangedEventArgs args)
{
    title = args.Title;
}
```
Thoughts?

**Comment by jsakamoto** [comment]
@Xeevis Thank you for letting me know!

I could reproduce this problem.

I'm going to fix this issue as soon as possible.

Please give me a few days.

**Comment by jsakamoto** [comment]
@Xeevis 
I published the new fixed versions just now.

- [Head Element Helper - Service - v.1.5.3-preview.1](https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement.Services/1.5.3-preview.1)
- [Head Element Helper - Components - v.5.4.3-preview.1](https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement/5.4.3-preview.1)
- [Head Element Helper - Server Prerendering - v.1.5.3-preview.1](https://www.nuget.org/packages/Toolbelt.Blazor.HeadElement.ServerPrerendering/1.5.3-preview.1)

Could you try it out?

**Comment by Xeevis** [comment]
@jsakamoto Thanks for the update, however not the problem I have, sorry if I haven't communicated it clearly. My problem is, that I'm trying to render title from a completely different component than the one setting it and that issue is still present for me. If `Title` component is declared on page `Counter.razor`, how to display current page title in say `Navbar.razor` which is child component of `MainLayout.razor`? This should ideally work with prerendering too.

**Comment by jsakamoto** [comment]
@Xeevis 
Why don't you place the only one `<Title>` component in the `Navbar.razor` if the `Navbar.razor` knows what the current page title should be?

Anyway, `OnAfterRenderAsync` and `OnAfterRenderAsync` are too late to affect the rendering result of server-side prerendering.
That is not a limitation of this library. That is by design and by the architecture of Blazor.
